#!/usr/bin/env bash
# Generates the portable single-file builds from the canonical skill.
# Run after editing anything under plugins/sharpen/skills/sharpen/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL="$ROOT/plugins/sharpen/skills/sharpen"
REFS="$SKILL/references"

strip_frontmatter() { awk 'NR==1 && /^---$/ {fm=1; next} fm && /^---$/ {fm=0; next} !fm' "$1"; }

# In the single-file builds there are no separate reference files, so retarget the
# in-body pointers at the appended sections.
inline_refs() {
  # shellcheck disable=SC2016  # backticks below are literal text in the sed pattern, not a subshell
  sed 's|Class-specific guidance lives in `references/by-task-type.md` — read that file only|Class-specific guidance is in the "Per-class checklists" section below — read only the part|'
}

# --- dist/sharpen.md : paste into any agent, or save as AGENTS.md ---
{
  echo "<!-- Generated by scripts/build.sh — edit plugins/sharpen/skills/sharpen/ instead. -->"
  echo
  strip_frontmatter "$SKILL/SKILL.md" | sed '/^## More$/,$d' | inline_refs
  echo
  echo "---"
  echo
  cat "$REFS/by-task-type.md"
  echo
  echo "---"
  echo
  cat "$REFS/examples.md"
} > "$ROOT/dist/sharpen.md"

# --- adapters/cursor/rules/sharpen.mdc ---
{
  cat <<'MDC'
---
description: Rewrite a rough or vague request into a concise execution-ready prompt for a coding agent. Use on "sharpen this", "optimize this prompt", "make this prompt better".
alwaysApply: false
---
MDC
  echo
  strip_frontmatter "$SKILL/SKILL.md" | sed '/^## More$/,$d' | inline_refs
  echo
  echo "---"
  echo
  cat "$REFS/by-task-type.md"
} > "$ROOT/adapters/cursor/rules/sharpen.mdc"

echo "built:"
echo "  dist/sharpen.md                     ($(wc -l < "$ROOT/dist/sharpen.md" | tr -d ' ') lines)"
echo "  adapters/cursor/rules/sharpen.mdc   ($(wc -l < "$ROOT/adapters/cursor/rules/sharpen.mdc" | tr -d ' ') lines)"
